name: firestore_exercise
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_auth: ^4.19.5
  intl: ^0.17.0
  firebase_core: ^2.31.0
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.5
  cloud_firestore: ^4.17.3
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  change_app_package_name: 
    git: https://github.com/Aksoyhlc/change_app_package_name.git


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
