name: gyumri_guide
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc:
  flutter_bloc:
  equatable:
  http:
  flutter_map: ^6.1.0
  geolocator: ^11.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.14
  provider: ^5.0.0
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0
  badges: ^2.0.2
  carousel_slider: ^4.0.0
  image_stack: ^2.1.1
  get_it: ^7.6.7
  image_picker: ^0.8.4+2  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - img/
